server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://movie.cdo2go0s62es.ap-southeast-2.rds.amazonaws.com:3306/movie
    username: admin
    password: 12345678


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true

api:
  prefix: /api/v1

jwt:
  expiration: 30  # 30s
  expiration-refresh-token: 60 # 1p
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
