server:
  port: 8088

spring:

  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 3000MB

  datasource:
    url: jdbc:mysql://localhost:3306/defty_movie_dev
#    url: jdbc:mysql://movie-advance.cn2k6s0skt43.ap-southeast-2.rds.amazonaws.com:3306/movie_advance
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Đảm bảo sử dụng đúng Dialect cho MySQL 8
        format_sql: true  # Hiển thị SQL đã định dạng đẹp (kèm theo tham số)
#        show_sql: true  # In câu lệnh SQL ra console
        use_sql_comments: true  # Thêm các chú thích SQL (nếu cần thiết)

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true

api:
  prefix: /api/v1

jwt:
  expiration: 600  # 10m
  expiration-refresh-token: 604800 # 7day
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

aws:
  access:
    key:
      id: AKIAZAI4GU3MNR2WWZEJ
  secret:
    access:
      key: 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
  s3:
    region: ap-southeast-2
    bucket:
      name: defty-movie
