server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/defty_movie_dev
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true

api:
  prefix: /api/v1/admin

jwt:
  expiration: 600  # 10 phut
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
